/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_androidjnitest_MainActivity */

#ifndef _Included_com_example_androidjnitest_MainActivity
#define _Included_com_example_androidjnitest_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_androidjnitest_MainActivity
 * Method:    add
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_androidjnitest_MainActivity_add
  (JNIEnv *, jobject);

/*
 * Class:     com_example_androidjnitest_MainActivity
 * Method:    max
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_androidjnitest_MainActivity_max
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
